---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    rg_name: CloudOps
    location: westus
  tasks:
    - name: Create a resource group
      azure_rm_resourcegroup:
        name: "{{ rg_name }}"
        location: "{{ location }}"
